### ISSUE TITLE
什么时候这个项目可以完成？

### ISSUE THREAD

**Issue by 2916247649** [leessmin/squadServerPanelS#1]
请问什么时候这个项目可以完成使用？

**Comment by leessmin** [comment]
准确来说，目前已经可以使用了，但是缺少Rcon,以及和squad server进行交互的能力。当初我在写这个项目的时候是看到哔哩哔哩有一个可以修改squad服务器配置文件的软件，然后心血来潮的开始了这个项目，当我写到一半的时候，我才知道一个叫Rcon的东西，所以我还得继续往下写，一直没有发布。但是Rcon这个功能能不能完成我也不清楚了，目前这个项目已经完成了我当时心血来潮时预计的目标了，但对比同款面板他仅仅只是缺少了Rcon以及和squad server交互的能力。感谢你关心这个项目的进度，我更欢迎大家来一起完善这个项目，谢谢！

**Comment by 2916247649** [comment]
可以写一个安装教程吗？非常感谢

**Comment by leessmin** [comment]
已经打包好了，你可以下载来试试看
